// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBljY4FjKVI1PTJ9DkjK3Y-fLOqaaERocg',
    appId: '1:105535173433:web:cbe588bc0c321d5f392ee8',
    messagingSenderId: '105535173433',
    projectId: 'tubes-8471c',
    authDomain: 'tubes-8471c.firebaseapp.com',
    storageBucket: 'tubes-8471c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOzjeDBD2mKi2l95fdBAn1KlLlN3ef18',
    appId: '1:105535173433:android:316cab9e303af92f392ee8',
    messagingSenderId: '105535173433',
    projectId: 'tubes-8471c',
    storageBucket: 'tubes-8471c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_RimVe2oYOYP7FxU58oxRFGgsc-0G9c',
    appId: '1:105535173433:ios:07d4b0f67aa373cb392ee8',
    messagingSenderId: '105535173433',
    projectId: 'tubes-8471c',
    storageBucket: 'tubes-8471c.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_RimVe2oYOYP7FxU58oxRFGgsc-0G9c',
    appId: '1:105535173433:ios:a77b7dfc93e7a3d0392ee8',
    messagingSenderId: '105535173433',
    projectId: 'tubes-8471c',
    storageBucket: 'tubes-8471c.appspot.com',
    iosBundleId: 'com.example.tubes.RunnerTests',
  );
}
